id: ICD766E66
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T07:17:54+00:00'
last_modified: '2022-06-07T21:57:34.051546+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25377
  title: བྱིས་རྩོམ་མེ་ཏོག་ཆུན་པོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BF64:
      image_group_id: I1KG25379
      title: ''
      total_pages: 222
      order: 1
      base_file: BF64.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
