id: P004319
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 11:10:18.988548
source_metadata:
  id: bdr:W1KG25377
  title: བྱིས་རྩོམ་མེ་ཏོག་ཆུན་པོ།
  author: ''
  volumes:
    305d0edd314a402d833f9f64d4297386:
      image_group_id: I1KG25379
      title: ''
      volume_number: 1
      total_pages: 222
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
